export const ADD_IMAGE = 'ADD_IMAGE';
export const ADD_IMAGE_SUCCESS = 'ADD_IMAGE_SUCCESS';
export const ADD_IMAGE_FAIL = 'ADD_IMAGE_FAIL';

export const DISPLAY_ERROR = 'DISPLAY_ERROR';
export const UPLOAD_IMAGE = 'UPLOAD_IMAGE';
